### ISSUE TITLE
RFC003 - Remove the PlatyPS Requirement for External Markdown

### ISSUE THREAD

**Issue by dalemorson** [SkillsFundingAgency/das-platform-automation#11]
### Description

The README currently states:

> All PowerShell scripts in the Infrastructure-Scripts folder must have external help documentation generated in markdown using the PlatyPS module.

### Proposal

I propose we remove this requirement (any mention of PlatyPS from the README) for the following reasons:

1. Reduce complexity of getting scripts into the repository.
2. Scripts should already include comment based help and any useful inline comments.

We can always add this later if we find we need some external documentation outside of the scripts.

**Comment by chelnak** [comment]
The tests should pick up missing help anyway 🐔

**Comment by dalemorson** [comment]
Raised PR to close this RFC: https://github.com/SkillsFundingAgency/das-platform-automation/pull/12

**Comment by EwanNoble** [comment]
Resolved
