### ISSUE TITLE
RFC004 - Release versioning

### ISSUE THREAD

**Issue by EwanNoble** [SkillsFundingAgency/das-platform-automation#15]
### Description

We are now publishing the infrastructure scripts as release assets and tagging releases using Gitversion, we need a consistent versioning plan going forward.

### Proposal

Initial proposal, [semver](https://semver.org/):

- Major increments: Breaking changes
- Minor increments: New scripts
- Patch increments: Non-breaking updates to existing scripts

**Comment by dalemorson** [comment]
How can we control the increment types?

**Comment by EwanNoble** [comment]
We can do this in commit messages:
https://gitversion.readthedocs.io/en/latest/more-info/version-increments/

- Major: +semver: major
- Minor: +semver: minor
- Patch: This is automatically incremented for every merge to master if the previous two haven't been incremented

**Comment by dalemorson** [comment]
Shall I add this to the README with examples?

**Comment by EwanNoble** [comment]
> Shall I add this to the README with examples?

If we are in agreement 🙂 @chelnak

**Comment by chelnak** [comment]
Agreed ✔️

**Comment by dalemorson** [comment]
PR open for initial draft: https://github.com/SkillsFundingAgency/das-platform-automation/pull/27

**Comment by dalemorson** [comment]
PR https://github.com/SkillsFundingAgency/das-platform-automation/pull/27 has now been approved and merged. RFC closed.
