### ISSUE TITLE
RFC005 - Add Shared Infrastructure deployment templates and documentation 

### ISSUE THREAD

**Issue by chelnak** [SkillsFundingAgency/das-platform-automation#18]
# Description 
Shared infrastructure deployment templates are currently stored in a private repository in Azure DevOps. There have been some changes to add networking support and improve the layout and deployment approach. 

It would be ideal to have all of our core automation stored and managed together and open source.

# Proposal
#17 adds the new templates to the repository along with a brief readme and a new deployment script.

**Comment by dalemorson** [comment]
@chelnak has created a new repository for this [here](https://github.com/SkillsFundingAgency/das-shared-infrastructure). Closing this RFC.
