### ISSUE TITLE
RFC001 - Local variables should be PascalCase

### ISSUE THREAD

**Issue by chelnak** [SkillsFundingAgency/das-platform-automation#7]
## Description
Currently the documentation states that local variables should be `camelCase`.

https://github.com/SkillsFundingAgency/das-platform-automation#naming-conventions

## Proposal
Local variables should be `PascalCase` so that they align with our previous development style.

**Comment by EwanNoble** [comment]
👍

**Comment by dalemorson** [comment]
I have raised a PR to reflect the change from Camel to Pascal case for local variables. https://github.com/SkillsFundingAgency/das-platform-automation/pull/9

**Comment by dalemorson** [comment]
Local variables are now required to be `PascalCase`. All current scripts in Master branch use the required local variable naming convention. The README.md has also been updated.
