### ISSUE TITLE
RFC002 - Enforce forward-slashes in file paths for compatibility with Unix operating systems

### ISSUE THREAD

**Issue by EwanNoble** [SkillsFundingAgency/das-platform-automation#8]
## Description
The documentation currently doesn't mention cross-platform compatibility which I think is something we should be aiming for.

## Proposal
Enforce via documentation the use of forward slashes ('/') so that the scripts can be run on different platforms.

**Comment by dalemorson** [comment]
I have raised a PR https://github.com/SkillsFundingAgency/das-platform-automation/pull/9 to ensure the README.md Helper Script Checklist table has a Should requirement for using forward slashes for platform compatibility.

**Comment by dalemorson** [comment]
This has now been added to the README.md as part of PR https://github.com/SkillsFundingAgency/das-platform-automation/pull/9.
